# Generated by Django 5.0.4 on 2024-04-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.TextField(),
        ),
    ]
