# Generated by Django 5.0.4 on 2024-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                (
                    "clients",
                    models.ManyToManyField(related_name="gyms", to="main.the_client"),
                ),
                (
                    "trainers",
                    models.ManyToManyField(related_name="gyms", to="main.the_trainer"),
                ),
            ],
        ),
    ]
