# Generated by Django 3.2.25 on 2024-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
